### ISSUE TITLE
API交易没有完成APP的任务

### ISSUE THREAD

**Issue by dream10201** [longportapp/openapi-go#62]
交易了任务没有完成

**Comment by Kikkon** [comment]
@dream10201  方便提供memberid吗，如果不方便的话给到订单号也可以，方便我们定位下问题

**Comment by dream10201** [comment]
> @dream10201 方便提供memberid吗，如果不方便的话给到订单号也可以，方便我们定位下问题

你可能误解了，我是说通过 SDK进行的股票交易，手机APP的任务没有完成，就是那个获取完成任务获取金币的

**Comment by dream10201** [comment]
这个界面的任务：
![image](https://github.com/user-attachments/assets/77f887b4-c521-47eb-9525-df43108b3e6d)

**Comment by Kikkon** [comment]
@dream10201 通过SDK下成功的订单号可以提供下吗

**Comment by dream10201** [comment]
@Kikkon 委托单号：1046432776318910464

**Comment by Kikkon** [comment]
@dream10201  目前通过openapi交易，已经可以被正常判定为完成交易任务。按照历史交易订单已补发任务币到账号中，请注意查收
